### ISSUE TITLE
SPOHubSite Get-TargetResource Issues when No Emails Assigned to Group

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Office365DSC#101]
#### Details of the scenario you tried and the problem that is occurring
I am faced with a situation where the Hub Site Principals are groups, but they don't have any emails assigned. We need to figure out how to better handle these scenarios.

#### Verbose logs showing the problem
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
Alpha

**Comment by NikCharlebois** [comment]
@ykuijs can you have a look?

**Comment by NikCharlebois** [comment]
Group Type is "Security"

**Comment by ykuijs** [comment]
Yes, will do!
