### ISSUE TITLE
O365Group Cannot export office groups

### ISSUE THREAD

**Issue by miroslavkoptik** [microsoft/Office365DSC#119]
When I am running export on one of our tenants, I cant get export of office groups to work. All other options work, but this one doesnt. Extracting failes without any exception. On other tenant this works just fine. Screenshots of selected options and from console:
![1](https://user-images.githubusercontent.com/45433186/59848819-9ef6fa00-9355-11e9-87dc-da5b1bb58a35.PNG)
![2](https://user-images.githubusercontent.com/45433186/59848820-9f8f9080-9355-11e9-9efe-902497b8fc30.PNG)

**Comment by NikCharlebois** [comment]
Thanks Michael, Can you please give my latest branch a try? Download the module manually and replace it manually:
https://github.com/NikCharlebois/Office365DSC/archive/Dev.zip

Delete the existing module you have under C:\Program files\WindowsPowerShell\Modules\Office365DSC

Repleace from what's in the .zip file:

[RootZip]\Office365DSC-Dev\Modules\Office365DSC\

**Comment by NikCharlebois** [comment]
@miroslavkoptik this latest branch includes a new LogEngine we are currently trying out internally. This will ensure the extraction continues whenever issues are encountered, but will generate an Error log within the execution folder listed encountered errors. Try running it with the O365Group option selected and see if it completes, and if it does, please parse the content of the error log in here.

**Comment by NikCharlebois** [comment]
@miroslavkoptik any updates on this? Thanks

**Comment by miroslavkoptik** [comment]
Thank you very much for the great support, but we have changed the technology in the meanwhile so we are no longer blocked by this issue. I might still test it in the free time if it helps, but its not blocking us anymore.

**Comment by NikCharlebois** [comment]
Ok thanks, and keep us posted
