### ISSUE TITLE
O365Group: Tenant (organization) name is extracted explicitly for Members

### ISSUE THREAD

**Issue by evgueniz** [microsoft/Office365DSC#130]
#### Details of the scenario you tried and the problem that is occurring
Extracted users and groups from my O365 tenant. While user configuration is indeed decoupled from the tenant name:
UserPrincipalName = "user1@**$($ConfigurationData.NonNodeData.OrganizationName)**"; 
Group memberships contain tenant name explicitly:
Members = @("user1@**contoso.com**","user2@**contoso.com**");

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Export members with $($ConfigurationData.NonNodeData.OrganizationName) instead of the actual organization name.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
N/A
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.0.0.8

**Comment by NikCharlebois** [comment]
@evgueniz Fixes have been implemented on GitHub, please grab the latest version of the module from this GitHub repo, test the changes and confirm that the issues identified above has been fixed. I will  proceed to closing the issue once I've received confirmation that it is working as expected. Thanks
