### ISSUE TITLE
O365OrgCustomizationSettings

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Office365DSC#136]
### Description
When trying to configure Security and Compliance components for the first time on certain tenants, you will get the following error back:

_The command you tried to run isn't currently allowed in your organization. To run this        command, you first need to run the command: Enable-OrganizationCustomization.                     + CategoryInfo          : NotSpecified: (Microsoft.Excha...AntiPhishPolicy:) [], CimExce     ption                                                                                          + FullyQualifiedErrorId : [Server=YQBPR0101MB0851,RequestId=4feee150-d5e9-4d98-aaa2-c8e4     33c8bb8b,TimeStamp=7/5/2019 1:01:17 PM] [FailureCategory=Cmdlet-InvalidOperationInDehydr     atedContextException] FDC3D516,Microsoft.Exchange.Management.SystemConfigurationTasks.Ne     wAntiPhishPolicy                                                                                 + PSComputerName        : Localhost_

It would be useful to have a resource to handle the enabling of OrganizationCustomization, which would run Enable-OrganizationCustomization in the background.

### Proposed properties
- IsSingleInstance
- Enabled [$true|$false]

### Special considerations or limitations
There doesn't seem to be the equivalent Disable cmdlet, therefore we may want to prevent Enabled = $false

**Comment by andikrueger** [comment]
You can assign me on this one. See PR #231
