### ISSUE TITLE
SPOSite for Groups

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Office365DSC#173]
#### Details of the scenario you tried and the problem that is occurring
The SPOSite Resource currently doesn't let you specify Group#0 as a template. This is to prevent users from creating the group site via the SPOSite resource. Instead they should use the O365Group restource to do so. However there are cases where we want to update the settings for the Group#0 site collection associated with the group. The resource should handle the case where the Group#0 site already exists and update its property.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
If Group#0 is specified, the resource should check to make sure the site already exists. If it doesn't, it should throw an error saying that the site must be created first using the O365Group resource. 

If the site exists, then it should proceed to simply updating its properties.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.0.0.776

**Comment by ThorstenLoeschmann** [comment]
I can take this. @Nik please assign it to me, since I cannot happen to assign it to myself.
