### ISSUE TITLE
SPOTheme: Missing function

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Office365DSC#204]
#### Details of the scenario you tried and the problem that is occurring
The SPOTheme resource is calling into a function names **Convert-ExistingThemePaletteToHashTable** which doesn't exist.

#### Verbose logs showing the problem
Can't find function Convert-ExistingThemePaletteToHashTable

#### Suggested solution to the issue
Create the function or remove call to it.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

**Comment by NikCharlebois** [comment]
@ThorstenLoeschmann Can you please have a look? Thanks

**Comment by ThorstenLoeschmann** [comment]
Sure

**Comment by ThorstenLoeschmann** [comment]
Added the Convert-ExistingThemePaletteToHashTable function to Office365DSCUtil.psm1... Not sure why it was not in there anymore... just took it from a older backup of the file :)

**Comment by NikCharlebois** [comment]
Fixed with PR #205
