### ISSUE TITLE
Dynamics 365 services configuration

### ISSUE THREAD

**Issue by shurick81** [microsoft/Office365DSC#215]
Hi, thanks for building this great thing! Is there any plan to do some automation for Dynamics 365 services in Office 365 subscription? Something along the same lines with this? https://docs.microsoft.com/en-us/powershell/dynamics365/customer-engagement/overview?view=dynamics365ce-ps

**Comment by NikCharlebois** [comment]
@shurick81 being very transparent here, this is not something we currently have on our radars, putting current priority on other workloads. However, it is definitively something we should be looking at in the future. If something from the community wants to take a stab at it, the team and I would be more than happy to review and integrate with the code base.
