### ISSUE TITLE
SPOTheme: No connection available. Use Connect-SPOService before running this CmdLet

### ISSUE THREAD

**Issue by shurick81** [microsoft/Office365DSC#218]
#### Details of the scenario you tried and the problem that is occurring

Trying to apply SPOTheme resource from the example.

#### Verbose logs showing the problem

https://gist.github.com/shurick81/ef227bd8313b51f6f1be712fc03bfb8c

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
    node localhost
    {

        SPOTheme SPTheme01
        {
            GlobalAdminAccount  = $credsGlobalAdmin
            Name                = "Unionen generisk"
            Palette             = @(MSFT_SPOThemePaletteProperty{
                                        Property = "themePrimary"
                                        Value = "#0078d4"
                                  }
                                  MSFT_SPOThemePaletteProperty{
                                      Property = "themeLighterAlt"
                                      Value = "#eff6fc"
                                  }
            )
        }

    }
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
```
get-module Office365DSC -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.0.0.1048 Office365DSC                        {Export-O365Configuration, Get-TimeZoneNameFromID, Confirm...
```

**Comment by NikCharlebois** [comment]
Issue was related to one of the logic path (when them didn't already exist) still referencing the SPO Management Shell cmdlets instead of the PnP ones. This resource was recently updated to remove all dependencies on SPO MS. Will be fixed in the linked PR.

**Comment by shurick81** [comment]
So it should use PnP cmdlets, ok. Sorry I still don't get it, how will it use Connect-PnPOnline if I haven't even specify site URL in the DSC resource?

**Comment by NikCharlebois** [comment]
We use the tenant name's from the GlobalAdminAccount provided to determine the SPO admin center dynamically. We then call Connect-PnPOnline on that URL.
