### ISSUE TITLE
Suggestion: Silent Install of SharePoint Online Management Shell

### ISSUE THREAD

**Issue by NikCharlebois** [Microsoft/Office365DSC#22]
The Office365DSC module is dependent on the Microsoft.Online.SharePoint.PowerShell module, however this module isn't enough to interact with SPO. The machine need the SharePoint Online Management Shell installed. We circumvented this issue in AppVeyor by executing a script that downloads the .msi installer and does a silent install. I am wondering now if we should add a check to the module to do the same thing if it is not present on the agent running the DSC? Our vision is that on a brand new machine, the mere fact of running Install-Module Office365DSC should allow the agent to execute a DSC script without having to do any additional manual intervention.

We would need to consider this in a server-less LCM approach as well.

**Comment by NikCharlebois** [comment]
Yes, this is a challenge. However, when you think about it, the only way users can currently interact with O365 with PowerShell is with the SPOManagement (or PnP) which requires the install anyway.

**Comment by ykuijs** [comment]
Agree, but then you can have an admin prepare the machine. If Office365Dsc tries to install the component, we cannot assume admin permissions.

**Comment by NikCharlebois** [comment]
True, then throwin a warning to let the user know that it needs to be installed manually as a prereq is probably our best option

**Comment by ykuijs** [comment]
Was just thinking:
What about prerequisite resources, like SPOPrereqs and EXOPrereqs? Then the user can choose themselves if they want the config to deploy the components or not.

We can even build in a version check to make sure you always have the most recent version of the component: You have version X installed and version Y is available on the Internet, so that newer version will be installed

**Comment by NikCharlebois** [comment]
That could work, but then, I would need to remove the PoSh module from the RequiredModule metadata in the psd1, which was my original issue. I'll need to think about it a bit more

**Comment by NikCharlebois** [comment]
Fixed with latest changes
