### ISSUE TITLE
SPOPropertyBag - Need to add Value as a Key parameter

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Office365DSC#232]
#### Details of the scenario you tried and the problem that is occurring
In many cases the same site collection will end up having the same Key name more than once, but with different case:

e.g. 

SPOPropertyBag 94b92452-3c32-43b5-a854-68c5f85d47b7
        {
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Key                  = "dlc_ExpirationLastRun";
            Url                  = "https://<site>";
            Value                = "03/10/2018 00:37:54";
        }
        SPOPropertyBag 19d11b88-f295-4f8a-a8e7-b1ad8e56f166
        {
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Key                  = "dlc_expirationlastrun";
            Url                  = "https://<site>";
            Value                = "11/4/2019 12:20:37 AM";
        }

#### Verbose logs showing the problem
Duplicate keys found

#### Suggested solution to the issue
Make the Value property become a Key parameter.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
SPOPropertyBag 94b92452-3c32-43b5-a854-68c5f85d47b7
        {
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Key                  = "dlc_ExpirationLastRun";
            Url                  = "https://<site>";
            Value                = "03/10/2018 00:37:54";
        }
        SPOPropertyBag 19d11b88-f295-4f8a-a8e7-b1ad8e56f166
        {
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Key                  = "dlc_expirationlastrun";
            Url                  = "https://<site>";
            Value                = "11/4/2019 12:20:37 AM";
        }

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise LTSC
OsOperatingSystemSKU : 125
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev Branch

**Comment by ykuijs** [comment]
Closed via PR #233
