### ISSUE TITLE
SCDLPComplianceRule: NotifyAllowOverride multiple values powershell error

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#236]
#### Details of the scenario you tried and the problem that is occurring

When running the resulting Office365TenantConfig.ps1 to generate the .mof file it throws an error related to NotifyAllowOverride of a SCDLPComplianceRule.

#### Verbose logs showing the problem

The error in question:

>Office365DSC\SCDLPComplianceRule : At least one of the values 'FalsePositive, WithJustification' >is not supported or
>valid for property 'NotifyAllowOverride' on class 'SCDLPComplianceRule'. Please specify only >supported values:
>FalsePositive, WithoutJustification, WithJustification.

#### Suggested solution to the issue

NotifyAllowOverride should be generated as an array and not a concatenated string.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```
SCDLPComplianceRule 81a38893-c3c2-45a3-a475-50f85d1716f7
        {
            ReportSeverityLevel                 = "Medium";
            NotifyUser                          = @("SiteAdmin","LastModifier","Owner");
            Disabled                            = $False;
            BlockAccessScope                    = "All";
            IncidentReportContent               = @("DocumentLastModifier","Detections","Severity","DetectionDetails","OriginalContent");
            GenerateIncidentReport              = @("SiteAdmin");
            Ensure                              = "Present";
            GlobalAdminAccount                  = $Credsglobaladmin;
            ContentContainsSensitiveInformation = MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Debit Card Number'
                id = '0e9b3178-9678-47dd-a509-37222ca96b42'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            };
            BlockAccess                         = $True;
            Name                                = "High volume of EU Sensitive content found";
            AccessScope                         = "NotInOrganization";
            Policy                              = "General Data Protection Regulation (GDPR)";
            NotifyAllowOverride                 = "FalsePositive, WithJustification";
        }
```

Windows 10 
Powershell 5.1
#### Version of the DSC module that was used ('dev' if using current dev branch)

Office365DCS 1.0.0.1048
ReverseDSC 1.9.4.6

**Comment by NikCharlebois** [comment]
@vinkobedek The issue has been fixed. Please validate that the latest Dev branch works
