### ISSUE TITLE
AppVeyor Wiki Processing Job Fails with CIMInstance[]

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Office365DSC#244]
Even though AppVeyor finishes successfully, the logs show several errors generating wiki pages from the .schema.mof files. It appears to be complaining about CimInstance arrays. We should investigate what the root cause is.

**Comment by ykuijs** [comment]
This issue should be fixed in [DscResource.Tests#357](/PowerShell/DscResource.Tests/issues/357)

**Comment by NikCharlebois** [comment]
It is indeed. Thanks for pointing this out @ykuijs
