### ISSUE TITLE
SPOStorageEntity contains only tenant scoped ones

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#253]
#### Details of the scenario you tried and the problem that is occurring
Don't know much about this resource but from what i can tell only tenant scoped storage entities are retrieved.
The O365DSCReverse script uses **Get-PnPStorageEntity** and from the documentation this defaults to tenant scoped. Site scoped are probably retrieved per site. 
#### Suggested solution to the issue
Cannot know more without investigating this further. But maybe call the Get-PnPStorageEntity for each of the site collections where the Site Collection App Catalog is enabled.

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
@vinkobedek you are right, this is only retrieved at the tenant level right now. Not sure we want to go to the point where we handle site collection specific settings. Is there a requirement to do so on your end?

**Comment by vinkobedek** [comment]
@NikCharlebois no requirement, just going through the loaded data and how it is loaded so the question arose if this should also be shown. I will close this issue since it's by design :)
