### ISSUE TITLE
SPOAPP resources not retrieved during Export-O365Configuration

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#254]
#### Details of the scenario you tried and the problem that is occurring
I tried to export the configuration but the SPOAccessControlSettings data was missing.
From what i can tell the appdatacatalog is being read from the wrong site collection and Find-PnpFile returns nothing
#### Verbose logs showing the problem
no logs, but the error is in O365DSCReverse.psm1 related to the Find-PnPFile -List "AppCatalog" command

#### Suggested solution to the issue
use the **Web** parameter of the  Find-PnPFile command in combination with the **$tenantAppCatalogUrl** 

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
@vinkobedek do you have a tenant wide app catalog defined? The resource currently only supports extracting SPOApp at the tenant level. Thanks

**Comment by vinkobedek** [comment]
@NikCharlebois you are correct. I have not been active with sharepoint online for quite some time and i've mistaken how it works/what's it for. I will close this issue.
