### ISSUE TITLE
Quiet parameter and the opening of the output directory

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#265]
We are calling Export-O365Configuration from C# with both the -Quiet and the -Path parameters. This causes problems since we do not expect a windows explorer window to pop up. We believe that in this case the output directory should not be opened up in explorer once the export process finishes. 

I see three solutions to this issues and will gladly provide a PR for any one of them once we establish the desired behavior.
1. do not open up the output directory if the Quiet switch was used
2. open the output directory only if no path was provided despite the Quiet switch
3. Provide a new switch that would indicate whether to open the output directory.

1 and 2 are breaking changes. 3 can be implemented with a default that matches the current behavior when the quiet switch is used (which i believe might not be the best). The problem with 3 though is that the default should obviously be to open it, but i cannot think of a good name for the switch that is not a negation.

I personally favor the second solution. if we requested that the export process stays quiet but did not specify a destination path then we can no longer be considered "quiet" since a location needs to be input. 

Thoughts?

**Comment by NikCharlebois** [comment]
@vinkobedek I agree 100% with your proposition from above. Option 2 is what we should proceed with. Thanks

**Comment by vinkobedek** [comment]
@NikCharlebois i see that you've assigned yourself to this. I have some code from before for a PR if you haven't already started working on this.

**Comment by NikCharlebois** [comment]
@vinkobedek all yours then mate.
