### ISSUE TITLE
SCComplianceCase DSR Case types are not retrieved

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#272]
#### Details of the scenario you tried and the problem that is occurring
I have some eDiscovery cases, but i also have some GDPR DSR cases. Only the eDiscovery ones are returned in the exported configuration.

#### Suggested solution to the issue
Repeat the Get-ComplianceCase call but with the **CaseType** parameter set to DSR. By default Get-ComplianceCase returns only eDiscovery cases.

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
@vinkobedek I'll handle the issues you've opened earlier today via a new PR. Thanks

**Comment by NikCharlebois** [comment]
@vinkobedek please review the latest code for fixes to 269-272

**Comment by vinkobedek** [comment]
@NikCharlebois thank you for the quick fixes.
