### ISSUE TITLE
SCComplianceTag FilePlanProperty contains only empty values

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#276]
#### Details of the scenario you tried and the problem that is occurring
the issue is related to ReverseDSC and Export-O365Configuration.. 
#### Suggested solution to the issue

I think that the issue is in the **Get-SCFilePlanProperty** function.
$JSONObject.Settings is actually a array of objects with {Key, Value} but is accessed as a dictionary.

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
@vinkobedek can you please validate that it is now working? Thanks

**Comment by vinkobedek** [comment]
@NikCharlebois yes, the file plan properties are now loaded correctly.
