### ISSUE TITLE
SCSensitivityLabel information is not exported in O365DSCReverse

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#279]
#### Details of the scenario you tried and the problem that is occurring
We noticed that SCSensitivityLabel resources are not included in the resulting ps1 file.
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
Fixed with PR #289

**Comment by NikCharlebois** [comment]
@vinkobedek Can you please confirm that the latest version fixes the issue? You can always run the new **Install-O365DSCDevBranch** which will automatically install the latest dev branch from Github.

**Comment by vinkobedek** [comment]
I can confirm that this is fixed. will close the issue.
