### ISSUE TITLE
TeamsUser telemetry is causing problems during extraction

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#291]
#### Details of the scenario you tried and the problem that is occurring
The extraction process for TeamsUser resources fails unless i remove the call to the telemetry engine
#### Verbose logs showing the problem
The term 'Add-O365DSCTelemetryEvent' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
#### Suggested solution to the issue
i think that this is just a matter of a missing import since the users are extracted in parallel jobs.
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
I actually believe the problem was related to the MaxProcesses variable not being properly defined with a default value. This will get fixed shortly. Thanks

**Comment by vinkobedek** [comment]
@NikCharlebois Just wanted to add that in addition to TeamsUser the problem is now also appearing for SPOPropertyBag and SPOUserProfileProperties. 
Best to check all resources where Start-Job is used.

**Comment by NikCharlebois** [comment]
@vinkobedek if you use a new environment (e.g. new VM) and install the latest version from the PowerShell Gallery, are you also getting the issue?

**Comment by vinkobedek** [comment]
No, the latest version from the powershell gallery appears to not have this issue.
The latest dev is still the same and the generated ps1 file contains no resources.

left: PS Gallery on a new server, right: latest dev
![image](https://user-images.githubusercontent.com/13213802/70986381-136ce480-20be-11ea-92e7-63422cf0f791.png)

**Comment by NikCharlebois** [comment]
@vinkobedek So the latest version from the gallery does work. I don't see it throwing any errors. For the machine on the right. Any chances that you would have multiple versions of the Office365DSC module co-existing?

**Comment by vinkobedek** [comment]
@NikCharlebois i tested the dev version on a new machine and everything works so i will close this issue and clean up whatever is bugging my machine.
