### ISSUE TITLE
PPPowerAppsEnvironment fails with a missing method exception

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#301]
#### Details of the scenario you tried and the problem that is occurring
`Export-O365Configuration -Quiet -ComponentsToExtract @("chckPPPower
AppsEnvironment")`

It fails with a missing method exception. some dll version mismatch. 
I tried to pinpoint it down, but did not get far. 

When i try to manually execute the commands, I get the results as expected (or better said, i get no error since i have no environments)
```powershell
Test-MSCloudLogin -Cloud $GlobalAdminAccount `
        -Platform PowerPlatforms
Get-AdminPowerAppEnvironment
```
If I try to export the configuration, then it fails, except if it's in the same powershell session where I retireved the environments manually (the correct dll is loaded in the session).

I uninstalled all of the older versions of the depencencies but no luck.

I can do additional digging if this is not reproducable.

#### Verbose logs showing the problem
[Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method named
'AcquireTokenByRefreshToken'.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerApps.Administration.PowerShell\2.0.26\Microsoft.PowerApps.
RestClientModule.psm1:65 char:14
+     $token = Get-JwtToken -Audience $audience
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-JwtToken], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,Get-JwtToken
#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1803
WindowsBuildLabEx    : 17134.1.amd64fre.rs4_release.180410-1804
OsLanguage           : en-US
OsMuiLanguages       : {en-US, hr-hr}

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
@vinkobedek Currently investigating this one. I got a similar issue in ONE of my environments yesterday. Putting priority on this issue.

**Comment by NikCharlebois** [comment]
@vinkobedek it appears that my error was related to something else. I am having a hard time replicating this in any of my environments. If you run the newly introduced function located at:
https://github.com/microsoft/Office365DSC/blob/Dev/Modules/Office365DSC/Modules/Office365DSCUtil.psm1#L1961

On a new environment. Are you still getting the error? This function will automatically install the latest Dev branch code along with all dependencies. Thanks

**Comment by vinkobedek** [comment]
I tried on a clean environment, and yes, everything works as expected. It is strange since my colleagues are experiencing the same issue.  I will close this issue, but may get back to you if we determine why it's happening on our end.
