### ISSUE TITLE
Issue with parameter 'location' and unitesstates instead of unitedstates

### ISSUE THREAD

**Issue by ngeorgeault** [microsoft/Office365DSC#308]
Just tried to export Office 365 Configuration using Export-O365Configuration function.
I just selected Teams on the selection screen and process failed without any further details from the command line but this details from the log file:
"Cannot validate argument on parameter 'Location'. The argument "unitedstates" does not belong to the set "canada,unitesstates,europe,asia,australia,india,japan,unitedkingdom,unitedstatesfirstrelease,southamerica,france,usgov" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again."

It seams, unitedstates argument is just written as unitesstates in the ValidateSet Attribute.

OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

office365DSC version: 1.0.1.1395

**Comment by NikCharlebois** [comment]
@ngeorgeault , yes there is clearly an error with the export of the allowed values in the PPPowerAppsEnvironment resource. However, this should not affect the Teams Workload, and should not be thrown when doing an Export. I will create a PR to have this fixed. In the meantime, try an unattended extract of Teams:

$creds = Get-Credential
Export-TargetResource -GlobalAdminAccount $creds -Quiet -Workloads Teams

**Comment by NikCharlebois** [comment]
Fixed
