### ISSUE TITLE
SCFilePlanPropertySubCategory items with custom category parents fail to extract

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#315]
#### Details of the scenario you tried and the problem that is occurring
I created some custom categories and subcategories in the compliance center: https://protection.office.com/retentionlabels.
It seems that subcategories of custom categories are not handled correctly and not extracted.
The extraction process completes and everything can be compiled, but some of the subcategories are missing.
#### Verbose logs showing the problem
```
Get-TargetResource : Cannot bind argument to parameter 'Category' because it is an empty string.
At C:\GitProjects\Office365DSC\Modules\Office365DSC\DSCResources\MSFT_SCFilePlanPropertySubCategory\MSFT_SCFilePlanProp
ertySubCategory.psm1:201 char:38
+         $result = Get-TargetResource @params
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-TargetResource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-TargetResource
```

#### Suggested solution to the issue
The issue seems to be that the parent categories are matched by id and the id of custom categories is something like 
`FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/M365x233468.onmicrosoft.com/Configuration/category1 ` and not` CN={guidThatIsTheSameAsParentId}` that the current code seems to expect.

I think that it would be better to match by the `Guid` or the `ExchangeObjectId` of the parent category since these appear to correspond wit `$subcategory.ParentId`.

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by vinkobedek** [comment]
Forgot to mention. for some reason it would seem that the last correctly extracted subcategory gets repeated and fills in for the one that should have been extracted, so the exported configuration contains  both data that is missing and data that is duplicated.
``` powershell
        SCFilePlanPropertySubCategory 956d91fe-c494-437d-9be8-fb04f8663957
        {
            Category             = "Contracting";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Name                 = "SubCategory1";
        }
        SCFilePlanPropertySubCategory c28b292b-55d1-4983-886d-683f08a4e5d0
        {
            Category             = "Contracting";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Name                 = "SubCategory1";
        }
        SCFilePlanPropertySubCategory cc4a2cfc-590b-4952-9a5b-6f5cfb1cbcd1
        {
            Category             = "Contracting";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Name                 = "SubCategory1";
        }
        SCFilePlanPropertySubCategory b2b356f6-353b-42cf-8bc1-bb6728164ad4
        {
            Category             = "Contracting";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Name                 = "SubCategory1";
        }
```

**Comment by NikCharlebois** [comment]
@vinkobedek can you please confirm that this is now fixed for you? Thanks

**Comment by vinkobedek** [comment]
@NikCharlebois I confirm that this works correctly now .
