### ISSUE TITLE
Could not find mandatory property Identity.

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Office365DSC#322]
#### Details of the scenario you tried and the problem that is occurring
Created a full configuration Dump from an O365 tenant and compiled it into a mof file. Running Test-DscConfiguration resulted in the following error.
#### Verbose logs showing the problem
```
Test-DscConfiguration .\O365TenantConfig\ -Verbose
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = TestConfiguration,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer AZTESTVM2 with user sid S-1-5-21-***********.
VERBOSE: [AZTESTVM2]: LCM:  [ Start  Compare  ]
VERBOSE: [AZTESTVM2]: LCM:  [ *FAILED*Compare  ]     Completed processing compare operation. The operation returned False.
Could not find mandatory property Identity. Add this property and try again.
    + CategoryInfo          : ObjectNotFound: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 6
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 2.227 seconds

```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
_I created a full export from a nearly plain vanilla tenant._
I haven't been able to figure out in which block of the DSC file the identity is actually missing.
#### The operating system the target node is running

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

**Comment by SebastianGoers** [comment]
I'm almost certain the issue originates in the Teams section of the script.

**Comment by SebastianGoers** [comment]
I narrowed it down to the following. A MessagingPolicy is being created which has Identity = $null. Changing $null to some value allows the Test-DscConfiguration command to execute.
(I guess this must be some sort of default policy as I didn't create any)
```
       TeamsMessagingPolicy 76781925-dc33-451f-8136-c296ce81bbc3
        {
            AllowGiphy                    = $True;
            AllowImmersiveReader          = $True;
            AllowMemes                    = $True;
            AllowOwnerDeleteMessage       = $False;
            AllowPriorityMessages         = $True;
            AllowRemoveUser               = $True;
            AllowStickers                 = $True;
            AllowUrlPreviews              = $True;
            AllowUserChat                 = $True;
            AllowUserDeleteMessage        = $True;
            AllowUserTranslation          = $False;
            AudioMessageEnabledType       = "ChatsAndChannels";
            ChannelsInChatListEnabledType = "DisabledUserOverride";
            Description                   = $null;
            Ensure                        = "Present";
            GiphyRatingType               = "Moderate";
            GlobalAdminAccount            = $Credsglobaladmin;
            Identity                      = $null;
            ReadReceiptsEnabledType       = "UserPreference";
            Tenant                        = $null;
        }
```

**Comment by NikCharlebois** [comment]
@SebastianGoers was this $null policy extracted with Office365DSC? DO you also see other policies being extracted?

**Comment by SebastianGoers** [comment]
@NikCharlebois , yes indeed, I extracted this policy with Office365DSC. To narrow down the issue I was using the -Workload TEAMS option for my last export. There were other policies in the export, all of them contained values for Identity, e.g. "Tag:AllOn".

**Comment by NikCharlebois** [comment]
Actually the issue has nothing to do with Office365DSC, but with the way you are calling the Test-DSCConfiguration cmdlet. 

Test-DSCConfiguration is meant to assess the current .mof file in memory. You therefore need to run Start-DSCConfiguration on your configuration first, and then Run Test-DscConfiguration. When you execute Test-DSCConfiguration, you should never pass in a folder. The Identity parameter the cmdlet complains about is the name of your configuration folder. Either don't pass it to assess the current .mof in memory or use the -ReferenceConfiguration parameter, but point it to the .mof inside the folder and not to the folder itself.

Closing issue

**Comment by SebastianGoers** [comment]
Alright I tested it again the way you described it and it works. Sorry for the confusion, I cannot remember where I got that wrong syntax from - my bad.
