### ISSUE TITLE
EXO: Testing Antispam settings failes if they are not configured.

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Office365DSC#323]
#### Details of the scenario you tried and the problem that is occurring
Running a Test-DscConfiguration against spam settings returns an error.
#### Verbose logs showing the problem
```
PowerShell DSC resource MSFT_EXOHostedContentFilterPolicy  failed to execute Test-TargetResource functionality with
error message: Cannot validate argument on parameter 'EndUserSpamNotificationCustomFromAddress'. The argument "" does
not match the "^[a-zA-Z0-9.!Â£#$%&'^_{}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$" pattern. Supply an argument that
matches "^[a-zA-Z0-9.!Â£#$%&'^_{}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$" and try the command again.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

**Comment by NikCharlebois** [comment]
@SebastianGoers We've updated the looping logic for the extraction scenario in our latest release on GitHub. The plan is to have this released to the PowerShell Gallery on Wednesday. Any chances you could test the latest changes from GitHub and let us know if the issue is still happening? Thanks

**Comment by NikCharlebois** [comment]
Closing since we haven't heard back to validate that this is still on-going and given recent PR changes done.
