### ISSUE TITLE
EXOSafeAttachmentRule rule details are not extracted

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#330]
#### Details of the scenario you tried and the problem that is occurring
I created some safe attachment policies at https://protection.office.com/safeattachment . it appears as if not everything regarding the corresponding rules is loaded. I can see that the schema has these properties defined, and the configured rule data is visible in the security and compliance admin portal, but it is not extracted.
![image](https://user-images.githubusercontent.com/13213802/72350103-0c95b980-36de-11ea-92bc-7e9f5673e4a7.png)

**Comment by NikCharlebois** [comment]
@vinkobedek this has been fixed with the latest PR

**Comment by vinkobedek** [comment]
Thanks, looks good.
