### ISSUE TITLE
EXOSafeLinksRule details are not extracted

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#331]
#### Details of the scenario you tried and the problem that is occurring
I created some safe links policies at https://protection.office.com/safelinksconverged . it appears as if not everything regarding the corresponding rules is loaded. I can see that the schema has these properties defined, and the configured rule data is visible in the security and compliance admin portal, but it is not extracted.
![image](https://user-images.githubusercontent.com/13213802/72350988-c2add300-36df-11ea-85e5-bae99a8b3b06.png)

**Comment by NikCharlebois** [comment]
@vinkobedek  this has been fixed with the latest PR

**Comment by vinkobedek** [comment]
Thanks, looks good.
