### ISSUE TITLE
EXOHostedOutboundSpamFilterPolicy not being loaded through the UI

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#332]
#### Details of the scenario you tried and the problem that is occurring
In the UI there is a reference to _OutBound Spam Filter Policy_ with a value of _chckEXOOutboundSpamFilterPolicy_ and if i select this for load, nothing is extracted.
In the O365DSCReverse.psm1 file there is only _chckEXOHostedOutboundSpamFilterPolicy._ 
#### Suggested solution to the issue
rename chckEXOOutboundSpamFilterPolicy in the UI to chckEXOHostedOutboundSpamFilterPolicy if OutBound Spam Filter Policy does indeed denote the EXOHostedOutboundSpamFilterPolicy  resource.

**Comment by NikCharlebois** [comment]
@vinkobedek this has been fixed with the latest PR
