### ISSUE TITLE
SCComplianceCase only GDPR cases are extracted 

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Office365DSC#335]
#### Details of the scenario you tried and the problem that is occurring
the `$dscContent` variable in `MSFT_SCComplianceCase` is being reset before extracting GDPR cases, so only those are extracted, even thought the eDiscorvery ones were enumerated.

#### Suggested solution to the issue
remove the erronous assignment
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
Was already working on a fix. Will be merged soon

**Comment by NikCharlebois** [comment]
@vinkobedek can you please confirm that this has been fixed with the latest PRs? Thanks

**Comment by vinkobedek** [comment]
@NikCharlebois I have checked, and yes, it is working now. I will close this issue.
