### ISSUE TITLE
exceeded the  maximum number of connections allowed

### ISSUE THREAD

**Issue by robertreems** [microsoft/Office365DSC#359]
Hi there,

I'm testing this module in my personal test environment. And came accross the following error quite often:

Processing data from remote server outlook.office365.com failed with the following error message: [AuthZRequestId=6a8828f9-9ab8-4f5d-877a-196b1878450b][FailureCategory=AuthZ-AuthorizationException] Fail to create a runspace because you have exceeded the 
maximum number of connections allowed : 3 for the policy party : MaxConcurrency. Please close existing runspace and try again.
Policy: CN=GlobalThrottlingPolicy_dfd9ac7d-5673-4cd4-ae20-556bd0721f25,CN=Global Settings,CN=ExchangeLabs,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=eurprd05,DC=prod,DC=outlook,DC=com; 
Snapshot: Owner:	Sid~S-1-5-21-4216173473-1702484195-1916209044-11983967~WSMan~false
BudgetType:	WSMan
ActiveRunspaces:	3/3
Balance:	600000/1800000/-3000000
PowerShellCmdletsLeft:	200/200
ExchangeCmdletsLeft:	9223372036854775807/Unlimited
CmdletTimePeriod:	5
DestructiveCmdletsLeft:	9223372036854775807/Unlimited
DestructiveCmdletTimePeriod:	Unlimited
QueueDepth:	Unlimited
MaxRunspacesTimePeriod:	60
RunSpacesRemaining:	5/5
LastTimeFrameUpdate:	2/8/2020 8:16:13 AM
LastTimeFrameUpdateDestructiveCmdlets:	2/8/2020 7:50:00 AM
LastTimeFrameUpdateMaxRunspaces:	2/8/2020 8:16:13 AM
Locked:	False
LockRemaining:	00:00:00 For more information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:) [], CimException
    + FullyQualifiedErrorId : IncorrectProtocolVersion,PSSessionOpenFailed
    + PSComputerName        : localhost
 
The term 'Close-SessionsAndReturnError' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Close-SessionsAndReturnError:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost
 
The term 'Get-AcceptedDomain' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-AcceptedDomain:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost

So what am I doing?

I have the following configuration published to my Azure automation account: 

 EXOAcceptedDomain ExampleEmailDomain {
            Ensure              = 'Present'
            Identity            = 'xxx.org'
            GlobalAdminAccount  = $TenantCredential
        }

        EXOSharedMailbox Mailbox
        {
            DisplayName        = "Test"
            PrimarySMTPAddress = "Test@xxx.onmicrosoft.com"
            Aliases            = @("Joufflu@xxx.onmicrosoft.com", "Gilles@xxx.onmicrosoft.com")
            Ensure             = "Present"
            GlobalAdminAccount = $TenantCredential
        }

One Windows 2016 node pulls this configuration and enacts it. 

Perhaps I'm to impatient and after making an update to my configuration I usually run on the Windows 2016 node.
Start-DscConfiguration -Wait -Verbose -Force -UseExisting 
or
Update-DscConfiguration -Wait -Verbose

Off course waiting a few moments resolves the issue. So that is the workaround. I suspect not all connections are properly closed after enacting. Or, most likely I've made a mistake, and this purely me being impatient or did I make a configuration error?

Thanks in advance

**Comment by robertreems** [comment]
Well, I couldn't reproduce it anymore. As far as I know nothing has been changed, I'm sure I didn't update the O365 module. Must be my bad some how so I'll close this case

**Comment by stvnmbr1** [comment]
reopening this one

When deploying EXO modules, PSSessions are not closed properly at the end of DSC. Deploying eg. 6 EXO modules after each other gives a Maxconcurrency error.
This does break the further deployment of modules.
