### ISSUE TITLE
Documentation TeamsTeam Ensure parameter doesn't throw an error as stated in documentation

### ISSUE THREAD

**Issue by robertreems** [microsoft/Office365DSC#371]
The documentation says:
Description: Present is the only value accepted. Configurations using Ensure = 'Absent' will throw an Error!

This doesn't seems to be the case in my environment as I've used it succesfully to remove a team. Please see example below that worked perfectly:
        TeamsTeam TeamConfig {
            DisplayName                       = "TestTeam"
            **Ensure                            = 'absent'**
            Description                       = "Test team description"
            Visibility                        = "Private"
            MailNickName                      = "testteam"
            AllowUserEditMessages             = $true
            AllowUserDeleteMessages           = $false
            AllowOwnerDeleteMessages          = $false
            AllowTeamMentions                 = $false
            AllowChannelMentions              = $false
            AllowCreateUpdateChannels         = $false
            AllowDeleteChannels               = $false
            AllowAddRemoveApps                = $false
            AllowCreateUpdateRemoveTabs       = $false
            AllowCreateUpdateRemoveConnectors = $false
            AllowGiphy                        = $True
            GiphyContentRating                = "Moderate"
            AllowStickersAndMemes             = $True
            AllowCustomMemes                  = $True
            AllowGuestCreateUpdateChannels    = $false
            AllowGuestDeleteChannels          = $false
            GlobalAdminAccount                = $TenantCredential
        }

Please find verbose logging of team removal below:
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ Start  Resource ]  [[TeamsTeam]TeamConfig]
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ Start  Test     ]  [[TeamsTeam]TeamConfig]
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Testing configuration of Team TestTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Getting configuration of Team TestTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Checking for existance of Team TestTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Found Team TestTeam.
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Current Values: AllowAddRemoveApps=False; AllowChannelMentions=False; AllowCreateUpdateChannels=False; AllowCreateUpdateRemoveConnectors=False; AllowCr
eateUpdateRemoveTabs=False; AllowCustomMemes=True; AllowDeleteChannels=False; AllowGiphy=True; AllowGuestCreateUpdateChannels=False; AllowGuestDeleteChannels=False; AllowOwnerDeleteMessages=False; AllowStickersAndMemes=True; Allo
wTeamMentions=False; AllowUserDeleteMessages=False; AllowUserEditMessages=True; Description=Test team description; DisplayName=TestTeam; Ensure=Present; GiphyContentRating=moderate; GlobalAdminAccount=System.Management.Automation
.PSCredential; GroupID=d07cbf42-945f-4b4c-a039-2d79b000f710; MailNickName=testteam; Owner=(robert@reems.onmicrosoft.com); Visibility=Private
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Target Values: AllowAddRemoveApps=False; AllowChannelMentions=False; AllowCreateUpdateChannels=False; AllowCreateUpdateRemoveConnectors=False; AllowCre
ateUpdateRemoveTabs=False; AllowCustomMemes=True; AllowDeleteChannels=False; AllowGiphy=True; AllowGuestCreateUpdateChannels=False; AllowGuestDeleteChannels=False; AllowOwnerDeleteMessages=False; AllowStickersAndMemes=True; Allow
TeamMentions=False; AllowUserDeleteMessages=False; AllowUserEditMessages=True; Description=Test team description; DisplayName=TestTeam; Ensure=Absent; GiphyContentRating=Moderate; GlobalAdminAccount=System.Management.Automation.P
SCredential; MailNickName=testteam; Verbose=True; Visibility=Private
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Test-TargetResource returned False
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ End    Test     ]  [[TeamsTeam]TeamConfig]  in 3.4560 seconds.
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ Start  Set      ]  [[TeamsTeam]TeamConfig]
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Setting configuration of Team TestTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Getting configuration of Team TestTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Checking for existance of Team TestTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Found Team TestTeam.
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamConfig] Removing team TestTeam
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ End    Set      ]  [[TeamsTeam]TeamConfig]  in 4.2880 seconds.
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ End    Resource ]  [[TeamsTeam]TeamConfig]

I'm using a Windows 2016 Azure node using Import-DscResource -ModuleName 'Office365DSC' -moduleVersion 1.0.2.1589

Robert

**Comment by NikCharlebois** [comment]
Fixed with a previous PR. Closing issue, thanks for reporting
