### ISSUE TITLE
Error on EXOAcceptedDomain when type is "Internal Relay"

### ISSUE THREAD

**Issue by Kiwi675** [microsoft/Office365DSC#391]
### Details of the scenario you tried and the problem that is occurring
During création of MOF file, I have an error with Exo Accepted Domain of "Internal Relay" type

#### Verbose logs showing the problem
<img width="1091" alt="PowershellIssue" src="https://user-images.githubusercontent.com/19490168/75554693-247d8e80-5a3b-11ea-8b79-6049f24aebf0.png">

#### Suggested solution to the issue
Add Internal relay in Domain Type accepted

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
        EXOAcceptedDomain e4bcc237-1998-4a3a-8b5e-3e74ccdea6f0
        {
            DomainType           = "InternalRelay";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Identity             = "ttt.ttt";
            MatchSubDomains      = $False;
            OutboundOnly         = $False;
        }

#### The operating system the target node is running
Windows 10 and Windows Srever 2019

**Comment by NikCharlebois** [comment]
PR merged. Closing
