### ISSUE TITLE
SPOSettings: New resource to manage SPO settings

### ISSUE THREAD

**Issue by ykuijs** [Microsoft/Office365DSC#42]
### Description
Add a new resource to manage settings for SharePoint Online

### Proposed properties
All properties in Get-SPOTenant that are not OneDrive related.

**Comment by NikCharlebois** [comment]
Just wanted to follow-up on this thread. What's the final call :)? Who's working on what here?

**Comment by ThorstenLoeschmann** [comment]
I think we did our alignment in Teams and can close this one.

**Comment by NikCharlebois** [comment]
Closing issue. This is now handled by the SPOTenantSettings resource.
