### ISSUE TITLE
Could not find mandatory property Identity. Add this property and try again.

### ISSUE THREAD

**Issue by Kjagiella** [microsoft/Office365DSC#423]
Hello,

I'm starting to play with this module, looks very promising.
I successfully exported my configuration and compiled it into a .mof file.
However, when i try to apply my configuration file, i got the following error :

``PS C:\temp\DSCExtracts\O365TenantConfig>  Start-DSCConfiguration c:\temp\dscextracts\O365TenantConfig -Wait -Verbose -Force

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/
DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer EGT035 with user sid S-1-5-21-3871675178-986574495-4259269654-9114.
VERBOSE: [EGT035]: LCM:  [ Start  Set      ]
VERBOSE: [EGT035]: LCM:  [ End    Set      ]
Could not find mandatory property Identity. Add this property and try again.
    + CategoryInfo          : ObjectNotFound: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 6
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 11.475 seconds``

<img width="1106" alt="2020-03-24 20_03_22-Administrator_ Windows PowerShell ISE" src="https://user-images.githubusercontent.com/62619205/77466744-fbb6a200-6e0a-11ea-9bc7-f7dd920bd382.png">

Have you an idea ?
In the .mof file, i can find many fields named "Identity". The first one is my tenant name.

Thanks for your support,
Kevin JAGIELLA

**Comment by NikCharlebois** [comment]
@Kjagiella Can you please try using the latest version on GitHub (you can simply run Install-O365DSCDevBranch)? There have been some fixes I believe will address your issue. You will need to run the extract again. Thanks

**Comment by Kjagiella** [comment]
Hi,

Indeed, it works better with the dev branch.
Many thanks for your quick answer !

**Comment by NikCharlebois** [comment]
Thanks @Kjagiella  so is everything working for you now? Can we close the issue?

**Comment by Kjagiella** [comment]
Yes it could be closed.
Thanks again
