### ISSUE TITLE
AppVeyor Challenge

### ISSUE THREAD

**Issue by NikCharlebois** [Microsoft/Office365DSC#45]
#### Details of the scenario you tried and the problem that is occurring
AppVeyor automatically grabs the SharePoint Online Management Shell msi from the web and installs it on the Build Agent. However, whenever the link changes (new version released) like it happened on January 2nd, then AppVeyor crashes because it gets a 404 trying to download the msi. We need to upload a static version to some stable location.

#### Verbose logs showing the problem
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of SharePoint that is used (e.g. SharePoint 2016)
N/A

#### Version and build of PowerShell the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
N/A

**Comment by ykuijs** [comment]
Can't we add a specific version to the repo?

**Comment by NikCharlebois** [comment]
@ykuijs your recommendation was implemented. We now have a static version of the MSI included. Closing the issue.
