### ISSUE TITLE
Add Examples for each resource to the repo

### ISSUE THREAD

**Issue by ykuijs** [Microsoft/Office365DSC#53]
Currently there is only one example in the [Examples folder](https://github.com/Microsoft/Office365DSC/tree/Dev/Modules/Office365DSC/Examples). There should be an example for each available resource.

**Comment by desmay** [comment]
So TeamExample, SPOExample, EXOExample etc.. ?

**Comment by NikCharlebois** [comment]
@desmay This should follow the same structure as SharePointDSC. One file per resource in the example folder:
https://github.com/PowerShell/SharePointDsc/tree/dev/Modules/SharePointDsc/Examples/Resources

**Comment by desmay** [comment]
Gotcha I will working on the files for resources I created

**Comment by NikCharlebois** [comment]
Examples all created with previous PR
