### ISSUE TITLE
TeamsChannel Timing Issues

### ISSUE THREAD

**Issue by NikCharlebois** [Microsoft/Office365DSC#69]
#### Details of the scenario you tried and the problem that is occurring
If in the same config, you create a Team and then try to add a channel to it, the TeamsChannel resource fails and complains that the team doesn't exist. It seems to be a timing issue because if you re-run the same config a few seconds later then everything works fine. 

#### Verbose logs showing the problem
PowerShell DSC resource MSFT_TeamsChannel  failed to execute Test-TargetResource functionality with error message: Team with Name Collab Summit
doesnt exist in tenant

#### Suggested solution to the issue
Add a few retries in the TeamsChannel resource whenever the Teams is not found. Maybe just 6 times 5 seconds.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
TeamsTeam CollabSummit
        {
            DisplayName        = "Collab Summit"
            Description        = "This is me demoing the Teams Resource"
            GlobalAdminAccount = $GlobalAdmin
            Ensure             = "Present"
        }

        TeamsChannel DSCChannel
        {
            TeamName           = "Collab Summit"
            DisplayName        = "DSC Discussions"
            GlobalAdminAccount = $GlobalAdmin
            Ensure             = "Present"
        }
```

#### The operating system the target node is running
NA

**Comment by desmay** [comment]
@NikCharlebois  I'm on it

**Comment by NikCharlebois** [comment]
You rock! Thanks Derek
