### ISSUE TITLE
Change Test-PnPOnlineConnection parameter

### ISSUE THREAD

**Issue by desmay** [Microsoft/Office365DSC#83]
### Description 

The Test-PnPOnlineConnection has parameter called -SPOCentralAdminUrl

### Proposed properties
Rename SPOCentralAdminUrl to SPOSiteUrl. Some of the PNP cmdlets are scoped to site level so the connection doesn't always have to be tenant admin url

**Comment by desmay** [comment]
@NikCharlebois I can make changes to existing resources and implement this change if you agree with proposed changes.

**Comment by NikCharlebois** [comment]
HAha, I was actually juggling with this idea just yesterday evening. Please go ahead!

**Comment by desmay** [comment]
Actually maybe just SiteUrl since this is all SPO

**Comment by desmay** [comment]
updated parameter in pull request 82
