### ISSUE TITLE
Need to Build a Robust Logging Engine

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Office365DSC#86]
### Description
We need to ensure that the Extraction component (ReverseDSC) never stops whenever there are errors detected. We do need however to capture all of these errors, in a very structured way. Potential known errors should have an Error Code, and Stack Trace should be captured as much as possible. Upon finalizing the extraction, the error log should be stored wherever the client decides to store the extraction results and the client should be warned in the console that errors where encountered during the extraction.

We need to make the troubelshooting process as smooth as possible. A client does an extraction, something goes wrong, they get notified and they have a log file they can send us for further troubleshooting.

**Comment by ykuijs** [comment]
I am thinking about improving logging in SharePointDsc as well. The default logging in DSC often doesn't give you enough information to troubleshoot issues (or blocks access to logging, by keeping the log file in use), so you have no idea what it is doing at the moment or have to crack open the source code to find out what is going on.

Is this something you like to integrate into ReverseDsc or into Office365Dsc?
